"use client";

import { useRef } from "react";
import { gsap, ScrollTrigger, useGSAP, EASE } from "@/lib/gsap";
import { getPage } from "@/config/pages";
import { siteConfig } from "@/config/site";
import { Container } from "@/components/ui/Container";
import { Button } from "@/components/ui/Button";
import { Reveal } from "@/components/motion/Reveal";
import { SplitLines } from "@/components/motion/SplitLines";
import { Rule } from "@/components/motion/Rule";
import { MarkAnchor } from "@/components/motion/MarkFlight";
import { PageOpening } from "@/components/ui/PageOpening";
import { AuditRows } from "@/components/graphics/Schematic";
import { CTA } from "@/components/sections/CTA";

/**
 * FREE SEO AUDIT.
 *
 * ── This page is not trying to rank ─────────────────────────────────────────
 * "seo audit" is KD 73 and it is marked `conversionOnly` in the IA config for
 * that reason. It will not rank in year one and should not be counted as an
 * SEO miss when it does not. Its job is to convert traffic arriving from ads,
 * from the guides, and from the rest of the site.
 *
 * That changes how it is built. No keyword padding, no attempt to be
 * comprehensive, and one action repeated. It is a landing page wearing a
 * service page's URL.
 *
 * ── The argument ────────────────────────────────────────────────────────────
 * "Free audit" is the most devalued offer in this industry, because almost
 * every one is an automated score out of a hundred with a sales call attached.
 * So the page spends its first section on the difference rather than on the
 * benefits, since the reader's real question is not what an audit is, it is
 * what the catch is.
 */

const INCLUDED = [
  {
    t: "What is stopping you ranking now",
    c: "The specific things, on your site, in order of what they are costing you. Not a list of every issue a crawler can detect.",
  },
  {
    t: "What your competitors are doing that you are not",
    c: "Two or three of them, by name, the ones actually appearing above you for the searches that matter.",
  },
  {
    t: "Your Google Business Profile, checked properly",
    c: "Categories, services, areas, reviews. For a local business this is regularly where the biggest single gain is.",
  },
  {
    t: "What we would do first, and why",
    c: "In order, with reasoning. If the first thing is something you can do yourself, it will say so.",
  },
];

const NOT_INCLUDED = [
  "A score out of a hundred generated by a tool you could have run yourself.",
  "A forty page PDF, ninety percent of which is a crawler export.",
  "A list of every issue on the site with no indication of which ones matter.",
  "A sales call you have to sit through before you are shown anything.",
];

export function SeoAuditContent() {
  const page = getPage("seo-audit");
  const root = useRef<HTMLElement>(null);

  useGSAP(
    () => {
      const el = root.current;
      if (!el) return;
      if (window.matchMedia("(prefers-reduced-motion: reduce)").matches) return;

      ScrollTrigger.create({
        trigger: el,
        start: "top bottom",
        end: "bottom top",
        toggleClass: "is-alive",
      });

      gsap.utils.toArray<HTMLElement>("[data-rise]", el).forEach((node) => {
        if (node.getBoundingClientRect().top < window.innerHeight * 0.95) return;

        gsap.fromTo(
          node,
          { autoAlpha: 0, y: 22 },
          {
            autoAlpha: 1,
            y: 0,
            duration: 0.8,
            ease: EASE.expo,
            scrollTrigger: { trigger: node, start: "top 86%", once: true },
          }
        );
      });
    },
    { scope: root }
  );

  return (
    <main ref={root} className="pt-32 lg:pt-40">
      <PageOpening
        eyebrow="Free SEO audit"
        title={page.h1}
        titleMax="max-w-[16ch]"
        intro="Not a score out of a hundred. A person looking at your site, your listing and your competitors, and writing down what they find."
      />

      <Container className="mt-12 lg:mt-16">
        <Reveal y={16} className="flex flex-wrap items-center gap-6">
          <Button href="/contact/" size="lg">
            Get the audit
          </Button>
          <p className="text-small text-faint">
            Yours to keep. No call required to receive it.
          </p>
        </Reveal>
      </Container>

      {/* ── The catch, addressed first ───────────────────────────────────── */}
      <section className="mt-20 border-y border-line bg-surface py-(--spacing-section) lg:mt-28">
        <Container>
          <div className="lg:flex lg:items-start lg:gap-16 xl:gap-24">
            <div className="lg:w-[46%] lg:shrink-0">
              <SplitLines
                as="h2"
                className="max-w-[18ch] font-display text-h2 leading-[1.1] text-foreground"
              >
                <>
                  Why it is{" "}
                  <span className="text-accent">free</span>, plainly.
                </>
              </SplitLines>
            </div>

            <div className="mt-10 max-w-text lg:mt-0 lg:min-w-0 lg:flex-1">
              <p data-rise className="text-lead text-muted">
                Because it is the most efficient sales call we have, and because
                doing it properly filters out the businesses we would be wrong
                for before anyone wastes a month finding out.
              </p>
              <p data-rise className="mt-6 text-body text-muted">
                Some of the audits we send end with us saying the first fix is
                something you can do yourself in an afternoon. Those people
                mostly do it, and a fair number come back later. That is a
                slower business and a better one.
              </p>
              <p data-rise className="mt-6 text-body text-muted">
                You keep the document either way, and nothing in it depends on
                hiring us to act on.
              </p>
            </div>
          </div>
        </Container>
      </section>

      {/* ── What is in it ────────────────────────────────────────────────── */}
      <section className="py-(--spacing-section)">
        <Container>
          <Reveal y={14} className="flex items-center gap-4">
            <MarkAnchor size="w-3.5" />
            <p className="eyebrow shrink-0 text-accent">What is in it</p>
            <Rule className="flex-1" delay={0.15} />
          </Reveal>

          <div className="mt-12 lg:flex lg:items-start lg:gap-16 xl:gap-24">
            <div className="lg:w-[52%] lg:shrink-0">
              <ul>
                {INCLUDED.map((item, i) => (
                  <li
                    key={item.t}
                    data-rise
                    className="border-t border-line py-7 last:border-b"
                  >
                    <div className="flex items-baseline gap-4">
                      <span className="font-mono text-eyebrow tabular-nums text-accent">
                        {String(i + 1).padStart(2, "0")}
                      </span>
                      <h3 className="max-w-[24ch] font-display text-h4 leading-tight text-foreground">
                        {item.t}
                      </h3>
                    </div>
                    <p className="mt-3 max-w-text text-body text-muted lg:pl-10">
                      {item.c}
                    </p>
                  </li>
                ))}
              </ul>
            </div>

            <Reveal delay={0.15} className="mt-14 lg:mt-0 lg:min-w-0 lg:flex-1">
              <div className="rounded-card border border-line bg-surface p-6 sm:p-10">
                <AuditRows className="w-full" />
              </div>
              <p className="mt-5 text-small text-faint">
                A drawing of the shape. The real one has your site in it.
              </p>
            </Reveal>
          </div>
        </Container>
      </section>

      {/* ── What it is not ───────────────────────────────────────────────── */}
      <section className="border-y border-line bg-surface py-(--spacing-section)">
        <Container>
          <div className="rounded-card border border-line bg-background p-8 lg:p-14">
            <p className="font-mono text-eyebrow uppercase tracking-wider text-faint">
              What it is not
            </p>

            <SplitLines
              as="h2"
              className="mt-7 max-w-[20ch] font-display text-h2 leading-[1.1] text-foreground"
            >
              Four things every other free audit is.
            </SplitLines>

            <ul className="mt-12 grid gap-6 lg:grid-cols-2">
              {NOT_INCLUDED.map((n) => (
                <li key={n} data-rise className="flex gap-4">
                  <span aria-hidden className="shrink-0 text-line-strong">
                    &times;
                  </span>
                  <span className="max-w-md text-body text-muted">{n}</span>
                </li>
              ))}
            </ul>

            <p className="mt-12 max-w-text text-body text-foreground">
              If you have had one of those, you already know the document was
              not the product. The call was.
            </p>
          </div>
        </Container>
      </section>

      {/* ── How it works ─────────────────────────────────────────────────── */}
      <section className="py-(--spacing-section)">
        <Container>
          <SplitLines
            as="h2"
            className="max-w-[18ch] font-display text-h2 leading-[1.1] text-foreground"
          >
            Three steps, and one of them is yours.
          </SplitLines>

          <div className="mt-14 grid gap-4 lg:mt-20 lg:grid-cols-3">
            {[
              {
                t: "Send us the site",
                c: "The URL and roughly what you want more of. That is the whole form. Two minutes.",
              },
              {
                t: "We go and look",
                c: "Your site, your Google listing, the competitors ranking above you. Usually a day or two.",
              },
              {
                t: "You get it in writing",
                c: "Read it, act on it, or ignore it. There is no follow-up sequence attached.",
              },
            ].map((s, i) => (
              <article
                key={s.t}
                data-rise
                className="group h-full rounded-card border border-line bg-surface p-8 transition-colors duration-slow ease-out-quart hover:border-accent lg:p-10"
              >
                <span className="block font-display text-h2 tabular-nums leading-none text-accent">
                  {String(i + 1).padStart(2, "0")}
                </span>
                <span
                  aria-hidden
                  className="mt-7 block h-px w-full bg-line transition-colors duration-slow ease-out-quart group-hover:bg-accent/40"
                />
                <h3 className="mt-7 font-display text-h4 leading-tight text-foreground">
                  {s.t}
                </h3>
                <p className="mt-4 text-body text-muted">{s.c}</p>
              </article>
            ))}
          </div>

          <div className="mt-14 flex flex-wrap items-center gap-6">
            <Button href="/contact/" size="lg">
              Get the audit
            </Button>
            {siteConfig.email ? (
              <p className="text-small text-muted">
                Or email{" "}
                <a
                  href={`mailto:${siteConfig.email}`}
                  className="text-foreground underline decoration-line-strong underline-offset-4 transition-colors duration-base hover:text-accent hover:decoration-accent"
                >
                  {siteConfig.email}
                </a>{" "}
                with your URL.
              </p>
            ) : null}
          </div>
        </Container>
      </section>

      <CTA />
    </main>
  );
}
